import React, { useMemo } from 'react';
import { XCircle, Info } from 'lucide-react';

const ConfigModal = ({ config, onClose }) => {
    if (!config) return null;

    const formatJSON = (jsonString) => {
        try {
            const parsed = JSON.parse(jsonString);
            return JSON.stringify(parsed, null, 2);
        } catch {
            return jsonString;
        }
    };

    const computeLineDiff = (refLines, currLines) => {
        const diff = [];
        const maxLen = Math.max(refLines.length, currLines.length);
        
        for (let i = 0; i < maxLen; i++) {
            const refLine = i < refLines.length ? refLines[i] : null;
            const currLine = i < currLines.length ? currLines[i] : null;
            
            // Normalize for comparison (ignore IDs in lifecycle rules)
            const normalizedRef = refLine ? refLine.replace(/"ID":\s*"[^"]+",?/g, '') : null;
            const normalizedCurr = currLine ? currLine.replace(/"ID":\s*"[^"]+",?/g, '') : null;
            
            if (refLine === null) {
                diff.push({ type: 'added', refLine: '', currLine, lineNum: i + 1 });
            } else if (currLine === null) {
                diff.push({ type: 'removed', refLine, currLine: '', lineNum: i + 1 });
            } else if (normalizedRef === normalizedCurr) {
                diff.push({ type: 'equal', refLine, currLine, lineNum: i + 1 });
            } else {
                diff.push({ type: 'modified', refLine, currLine, lineNum: i + 1 });
            }
        }
        
        return diff;
    };

    // Always compute diff if we have a reference alias
    const diffLines = useMemo(() => {
        if (!config.referenceAlias || config.alias === config.referenceAlias) {
            return null;
        }

        // Get reference and current values (use empty string if not available)
        const refValue = config.referenceValue || '';
        const currValue = config.value || '';

        const refStr = refValue ? formatJSON(refValue) : '';
        const currStr = currValue ? formatJSON(currValue) : '';
        
        const refLines = refStr ? refStr.split('\n') : [];
        const currLines = currStr ? currStr.split('\n') : [];
        
        return computeLineDiff(refLines, currLines);
    }, [config]);

    return (
        <div className={`modal ${config ? 'active' : ''}`} onClick={onClose}>
            <div className="modal-content" style={{ maxWidth: '1200px', maxHeight: '85vh' }} onClick={(e) => e.stopPropagation()}>
                <div className="modal-header">
                    <h3 className="modal-title">
                        Configuration: {config.bucket}
                    </h3>
                    <button className="modal-close" onClick={onClose}>
                        <XCircle size={20} />
                    </button>
                </div>

                {/* Info note about ID differences */}
                <div style={{ 
                    padding: '12px 16px', 
                    backgroundColor: '#dbeafe', 
                    borderBottom: '1px solid #93c5fd',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '8px'
                }}>
                    <Info size={16} style={{ color: '#1e40af', flexShrink: 0 }} />
                    <span style={{ fontSize: '13px', color: '#1e40af' }}>
                        Note: Rule IDs are automatically generated by MinIO and will differ between sites. You can ignore ID differences.
                    </span>
                </div>
                
                {diffLines ? (
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0', maxHeight: 'calc(85vh - 140px)', overflowY: 'auto', border: '1px solid #d1d5db' }}>
                        {/* Reference Column (Left) */}
                        <div style={{ borderRight: '1px solid #d1d5db', backgroundColor: '#ffffff' }}>
                            <div style={{ 
                                padding: '8px 12px', 
                                backgroundColor: '#f3f4f6', 
                                borderBottom: '1px solid #d1d5db',
                                fontSize: '13px',
                                fontWeight: 600,
                                color: '#1f2937',
                                position: 'sticky',
                                top: 0,
                                zIndex: 1
                            }}>
                                Reference: {config.referenceAlias || 'N/A'}
                                {!config.referenceValue && (
                                    <span style={{ fontSize: '11px', color: '#6b7280', fontWeight: 400, marginLeft: '8px' }}>
                                        (Not Configured)
                                    </span>
                                )}
                            </div>
                            <div style={{ 
                                backgroundColor: '#ffffff', 
                                color: '#1f2937', 
                                fontSize: '12px',
                                fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
                                lineHeight: '1.5'
                            }}>
                                {diffLines.map((line, idx) => (
                                    <div 
                                        key={idx} 
                                        style={{ 
                                            display: 'flex',
                                            backgroundColor: 
                                                line.type === 'removed' ? '#ffebe9' : 
                                                line.type === 'modified' ? '#ffebe9' : 
                                                line.type === 'added' ? '#f6f8fa' :
                                                '#ffffff',
                                            borderLeft: line.type === 'removed' || line.type === 'modified' 
                                                ? '4px solid #ffebe9' 
                                                : '4px solid transparent'
                                        }}
                                    >
                                        <span style={{ 
                                            minWidth: '50px', 
                                            padding: '0 8px', 
                                            textAlign: 'right', 
                                            color: line.type === 'removed' || line.type === 'modified' ? '#24292f' : '#8c959f',
                                            userSelect: 'none',
                                            backgroundColor: 
                                                line.type === 'removed' ? '#ffebe9' : 
                                                line.type === 'modified' ? '#ffebe9' :
                                                line.type === 'added' ? '#f6f8fa' :
                                                '#ffffff'
                                        }}>
                                            {line.refLine ? line.lineNum : ''}
                                        </span>
                                        <span style={{ 
                                            minWidth: '25px',
                                            padding: '0 8px',
                                            textAlign: 'center',
                                            color: line.type === 'removed' || line.type === 'modified' ? '#cf222e' : 'transparent',
                                            userSelect: 'none',
                                            fontWeight: 700,
                                            backgroundColor: 
                                                line.type === 'removed' ? '#ffebe9' : 
                                                line.type === 'modified' ? '#ffebe9' :
                                                line.type === 'added' ? '#f6f8fa' :
                                                '#ffffff'
                                        }}>
                                            {(line.type === 'removed' || line.type === 'modified') && line.refLine ? '-' : ''}
                                        </span>
                                        <span style={{ 
                                            padding: '0 8px', 
                                            flex: 1,
                                            whiteSpace: 'pre',
                                            opacity: line.refLine ? 1 : 0.4,
                                            color: line.type === 'removed' || line.type === 'modified' ? '#24292f' : '#57606a'
                                        }}>
                                            {line.refLine || ' '}
                                        </span>
                                    </div>
                                ))}
                            </div>
                        </div>
                        
                        {/* Current Column (Right) */}
                        <div style={{ backgroundColor: '#ffffff' }}>
                            <div style={{ 
                                padding: '8px 12px', 
                                backgroundColor: '#f3f4f6', 
                                borderBottom: '1px solid #d1d5db',
                                fontSize: '13px',
                                fontWeight: 600,
                                color: '#1f2937',
                                position: 'sticky',
                                top: 0,
                                zIndex: 1
                            }}>
                                Selected: {config.alias}
                                {!config.value && (
                                    <span style={{ fontSize: '11px', color: '#6b7280', fontWeight: 400, marginLeft: '8px' }}>
                                        (Not Configured)
                                    </span>
                                )}
                            </div>
                            <div style={{ 
                                backgroundColor: '#ffffff', 
                                color: '#1f2937', 
                                fontSize: '12px',
                                fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
                                lineHeight: '1.5'
                            }}>
                                {diffLines.map((line, idx) => (
                                    <div 
                                        key={idx} 
                                        style={{ 
                                            display: 'flex',
                                            backgroundColor: 
                                                line.type === 'added' ? '#dafbe1' : 
                                                line.type === 'modified' ? '#dafbe1' : 
                                                line.type === 'removed' ? '#f6f8fa' :
                                                '#ffffff',
                                            borderLeft: line.type === 'added' || line.type === 'modified' 
                                                ? '4px solid #dafbe1' 
                                                : '4px solid transparent'
                                        }}
                                    >
                                        <span style={{ 
                                            minWidth: '50px', 
                                            padding: '0 8px', 
                                            textAlign: 'right', 
                                            color: line.type === 'added' || line.type === 'modified' ? '#24292f' : '#8c959f',
                                            userSelect: 'none',
                                            backgroundColor: 
                                                line.type === 'added' ? '#dafbe1' : 
                                                line.type === 'modified' ? '#dafbe1' :
                                                line.type === 'removed' ? '#f6f8fa' :
                                                '#ffffff'
                                        }}>
                                            {line.currLine ? line.lineNum : ''}
                                        </span>
                                        <span style={{ 
                                            minWidth: '25px',
                                            padding: '0 8px',
                                            textAlign: 'center',
                                            color: line.type === 'added' || line.type === 'modified' ? '#1a7f37' : 'transparent',
                                            userSelect: 'none',
                                            fontWeight: 700,
                                            backgroundColor: 
                                                line.type === 'added' ? '#dafbe1' : 
                                                line.type === 'modified' ? '#dafbe1' :
                                                line.type === 'removed' ? '#f6f8fa' :
                                                '#ffffff'
                                        }}>
                                            {(line.type === 'added' || line.type === 'modified') && line.currLine ? '+' : ''}
                                        </span>
                                        <span style={{ 
                                            padding: '0 8px', 
                                            flex: 1,
                                            whiteSpace: 'pre',
                                            opacity: line.currLine ? 1 : 0.4,
                                            color: line.type === 'added' || line.type === 'modified' ? '#24292f' : '#57606a'
                                        }}>
                                            {line.currLine || ' '}
                                        </span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                ) : (
                    <div style={{ 
                        backgroundColor: '#f6f8fa', 
                        color: '#24292f', 
                        padding: '16px', 
                        borderRadius: '6px',
                        fontSize: '12px',
                        fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
                        overflowX: 'auto',
                        maxHeight: 'calc(85vh - 100px)',
                        overflowY: 'auto',
                        border: '1px solid #d1d5db'
                    }}>
                        <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>
                            {formatJSON(config.value)}
                        </pre>
                    </div>
                )}
            </div>
        </div>
    );
};

export default ConfigModal;
